[Details]
  Icon = "icon/assets/app.png"
  Name = "GoXRay"
  ID = "com.github.goxray.client.app"
  Version = "0.0.1"
  Build = 56

[LinuxAndBSD]
  GenericName = "VPN Client"
  Categories = ["Network"]
  Comment = "VPN for XRay protocol"
  Keywords = ["vpn", "xray", "goxray", "gotun", "tun"]
